### ISSUE TITLE
Request: prebuilt docker container

### ISSUE THREAD

**Issue by tln** [aviaviavi/toodles#11]
That would make trying this out much easier!

**Comment by aviaviavi** [comment]
Great idea!

**Comment by mrala** [comment]
@aviaviavi, would you mind if I submitted a PR to add a Dockerfile?

**Comment by aviaviavi** [comment]
Not at all, thanks so much @mrala!

**Comment by fbartels** [comment]
@mrala still busy? Let me know if you've given up and I might have a stab at it.

**Comment by aviaviavi** [comment]
Reopening because I realize the "prebuilt" aspect of the issue still hasn't been satisfied quite as well as it could be, though it's a great start. 

This docker image is still very large (>3gb), and has all the things needed to build toodles, which it really doesn't need. We just need to automate building a docker image with a compiled binary and any static assets copied in. The docker image could then be very lean

**Comment by aviaviavi** [comment]
I haven't yet pushed anything to docker hub, planning to do that later tomorrow after merging #47

**Comment by aviaviavi** [comment]
https://hub.docker.com/r/aviaviavi/toodles/
